# 07 葡萄酒分类

In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
# 载入数据
data = np.genfromtxt('./data/wine_data.csv', delimiter=',')
x_data = data[:,1:]
y_data = data[:,0]
print(x_data.shape)
print(y_data.shape)

(178, 13)
(178,)


In [3]:
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3)

In [4]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test  =scaler.fit_transform(x_test)

In [5]:
mlp = MLPClassifier()
mlp.fit(x_train, y_train)

E:\software\Anaconda\Anaconda\envs\Kaggle\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [6]:
predictions = mlp.predict(x_test)
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00        19
         2.0       0.95      1.00      0.97        19
         3.0       1.00      0.94      0.97        16

    accuracy                           0.98        54
   macro avg       0.98      0.98      0.98        54
weighted avg       0.98      0.98      0.98        54



In [7]:
print(confusion_matrix(y_test, predictions))

[[19  0  0]
 [ 0 19  0]
 [ 0  1 15]]
